services:
  db:
    image: pgvector/pgvector:pg16 # Use a specific version
    container_name: ragstar_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-ragstar}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password} # Change this in production!
    ports:
      - "${POSTGRES_PORT:-5432}:5433" # Expose DB port to host if needed
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-ragstar}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend_django:
    image: ragstar/backend_django
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    container_name: ragstar_django
    ports:
      - "${APP_PORT:-8000}:8080" # Expose API server port
    env_file:
      - .env
    environment:
      # Use external DB URL if provided, otherwise use the 'db' service
      DATABASE_URL: ${EXTERNAL_POSTGRES_URL:-postgresql://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-ragstar}}
      APP_PORT: ${APP_PORT:-8000}
    depends_on:
      db:
        condition: service_healthy # Wait for DB to be ready
    # The command to run the app (replace the placeholder in Dockerfile or override here)
    # command: poetry run uvicorn ragstar.api.server:app --host 0.0.0.0 --port 8000
    restart: unless-stopped

  frontend_nextjs:
    image: ragstar/frontend_nextjs
    build:
      context: ./frontend_nextjs
      dockerfile: Dockerfile
    container_name: ragstar_frontend
    ports:
      - "${FRONTEND_PORT:-3001}:3000" # Expose Next.js app port (host:container)
    volumes:
      - ./frontend_nextjs:/app # Mount local code for development
      - /app/node_modules # Keep container node_modules
      - /app/.next # Keep container .next folder
    environment:
      NEXT_PUBLIC_API_URL: http://backend_django:8080/api # URL for the Django API
      NODE_ENV: development # Explicitly set development mode for Next.js
    depends_on:
      - backend_django
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
